import { Component } from '@angular/core';

@Component({
  selector: 'menu-offices',
  templateUrl: './offices.html',
  styleUrls: ['./offices.css']
})

export class MenuOffices {

  public cityName: string = 'No selected';
  public cities = [
    'PARC PARQUE',
    'PASEO COSTA DEL SUR',
    'SECT LANAUSSE',
    'URB EUGENE RICE',
    'URB GONZALEZ',
    'URB LA FABRICA',
    'URB MONTE SORIA 2',
    'VILLAS DEL COQUI',
    'AIBONITO',
    'BDA SAN LUIS',
    'BO LLANOS',
    'BRISAS DE AIBONITO',
    'COLINAS DE SAN FRANCISCO',
    'EST DEL LLANO',
    'EXT BELLA VISTA',
    'EXT SAN LUIS',
    'EXT VILLA ROSALES',
    'REPTO ROBLES',
    'URB BELLA VISTA',
    'URB BUENA VISTA',
    'URB GOLDEN VLG IV',
    'URB LA PROVIDENCIA',
    'VILLA DE LA ROSA',
    'VILLA ROSALES',
    'VILLAS DEL COQUI',
    'ANASCO',
    'BRISAS DE ANASCO',
    'EST DE VALLE VERDE',
    'JARD DE ANASCO',
    'PASEO DEL VALLE',
    'REPTO DAGUEY',
    'URB SAN ANTONIO',
    'ANGELES',
    'ARECIBO',
    'ALT DE JUNCOS',
    'ALT DE SAN FELIPE',
    'BDA DUHAMEL',
    'BO EL PASAJE',
    'BO ISLOTE',
    ',BO ISLOTE II',
    'BO JAREALITOS',
    'BO OBRERO',
    'BO SANTANA',
    'COMUNIDAD BUENOS AIRES',
    'EST DE ARECIBO',
    'EST DE BALSEIRO',
    'EXT MARISOL',
    'EXT TANAMA',
    'EXT VILLA LOS SANTOS I',
    'EXT VILLA LOS SANTOS II',
    'HACIENDA TOLEDO',
    'JARD DE ARECIBO',
    'JARD DE SAN RAFAEL',
    'PARC MATTEY',
    'PARC NAVAS',
    'PARC PEREZ',
    'ADJUNTAS',
    'COLINAS DEL GIGANTE',
    'JARD DE ADJUNTAS',
    'URB SAN JOAQUIN',
    'CASTANER',
    'ADJUNTAS',
    'AGUADA',
    'ALTS DE AGUADA',
    'BO GUANIQUILLA',
    'COMUNIDAD LAS FLORES',
    'EXT LOS ROBLES',
    'URB ISABEL LA CATOLICA',
    'AGUADILLA',
    'RAMEY',
    'BDA CABAN',
    'BDA ESTEVES',
    'BO BORINQUEN',
    'BO CEIBA BAJA',
    'EXT EL PRADO',
    'EXT MARBELLA',
    'REPTO JIMENEZ',
    'REPTO JUAN AGUIAR',
    'REPTO LOPEZ',
    'REPTO TRES PALMAS',
    'SECT LAS VILLAS',
    'URB BORINQUEN',
    'URB EL PRADO',
    'URB ESTEVES',
    'URB GARCIA',
    'URB LAS AMERICAS',
    'URB LAS CASITAS COUNTRY CLUB',
    'URB MALEZA GDNS',
    'URB MARBELLA',
    'URB RAMEY',
    'URB RUBIANES',
    'URB SAN CARLOS',
    'URB SANTA MARTA',
    'URB VICTORIA',
    'VILLA ALEGRIA',
    'VILLA LINDA',
    'VILLA LYDIA',
    'VILLA UNIVERSITARIA',
    'VILLAS DE ALMERIA',
    'VISTA ALEGRE',
    'VISTA VERDE',
    'AGUADILLA',
    'RAMEY',
    'AGUADILLA',
    'AGUAS BUENAS',
    'EST DEL RIO',
    'MANS DE AGUAS BUENAS',
    'URB SAN ANTONIO',
    'AGUIRRE',
    'EST DE TRINITARIA',
    'EXT EL COQUI',
    'PARC CABASA',
    'MONITOR',
    'TAURUS',
    'WESTWOOD',
    'OLD TAPPAN',
    'RIVER VALE',
    'RIVERVALE',
    'WOODCLIFF LAKE',
    'WESTWOOD',
    'WOODCLIFF LK',
    'WHARTON',
    'WHIPPANY',
    'WHIPPANY',
    'WHITEHOUSE',
    'WHITEHOUSE STATION',
    'WHITE HSE STA',
    'WHITE HOUSE STATION',
    'WOODBRIDGE',
    'WYCKOFF',
    'BRONX',
    'BRONX',
    'HIGHBRIDGE',
    'STADIUM',
    'UNIVERSITY HEIGHTS',
    'BRONX'
  ]

  constructor() {  }

  public selectCity(cityName: string) {
    this.cityName = cityName;
  }

}
